name: DockerImageBuild

on: push   
    
jobs:

  buildToDockerHub:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Login to dockerHUB
      uses: docker/login-action@v4.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Image
      run: |
          docker build -t frankisinfotech/bulb:$GITHUB_RUN_NUMBER .
          docker push frankisinfotech/bulb:$GITHUB_RUN_NUMBER

  buildToAWSPrivateECR:
    needs: buildToDockerHub
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: AWS ECR Docker Login
      uses: elgohr/ecr-login-action@v3
      with:
        access_key: ${{ secrets.ACCESS_KEY }}
        secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
        region: ${{ secrets.REGION }}
          

    - name: Authenticate to ECR
      run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 798470206542.dkr.ecr.eu-west-1.amazonaws.com
      # run: |
      #     docker build -t frankisinfotech/bulb:$GITHUB_RUN_NUMBER .
      #     docker push frankisinfotech/bulb:$GITHUB_RUN_NUMBER
